name: wallpaper_dope
description: A new Flutter project.


publish_to: 'none' 

version: 6.2.2+8.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  

  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  provider: ^4.3.1
  http: ^0.12.2
  google_fonts: ^1.1.0
  sqflite: 
  path: 
  path_provider:
  wallpaper_manager: 
  dio: ^3.0.10
  permission_handler: ^5.0.1+1
  liquid_progress_indicator: ^0.3.2
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  http_parser: ^3.1.4
  image_picker: ^0.6.7+6
  mime_type: ^0.3.0
  animated_icon_button: ^0.3.0
  url_launcher: 
  like_button: ^1.0.1
  custom_splash: ^0.0.2
  cached_network_image: ^2.3.1
  adaptive_dialog: ^0.7.5+3
  flutter_staggered_grid_view: ^0.3.2
  random_color_scheme: ^0.0.1





dev_dependencies:

  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - lang/en.json
    - lang/es.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
